name: txt.fliglio.com
description: foo
url: txt.fliglio.com
markdown: kramdown
highlighter: pygments
permalink: /:year/:month/:title/
excerpt_separator: <!--more-->
encoding: utf-8
exclude: ["Dockerfile"]
